In [199]:
from sklearn.datasets import load_iris

In [200]:
iris = load_iris()

In [201]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [202]:
import pandas as pd

In [203]:
file = pd.DataFrame(iris.data, columns = iris.feature_names)

In [204]:
file['Type'] = iris.target

In [205]:
file.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Type  
0     0  
1     0  
2     0  
3     0  
4     0

In [206]:
file.groupby(file.Type).describe()

sepal length (cm)                                              \
                 count   mean       std  min    25%  50%  75%  max   
Type                                                                 
0                 50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
1                 50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
2                 50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

     sepal width (cm)         ... petal length (cm)      petal width (cm)  \
                count   mean  ...               75%  max            count   
Type                          ...                                           
0                50.0  3.428  ...             1.575  1.9             50.0   
1                50.0  2.770  ...             4.600  5.1             50.0   
2                50.0  2.974  ...             5.875  6.9             50.0   

                                                
       mean       std  min  25%  50%  75%  max  
Type                                            
0     0.246  0.105386  0.1  0.2  0.2  0.3  0.6  
1     1.326  0.197753  1.0  1.2  1.3  1.5  1.8  
2     2.026  0.274650  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

In [207]:
file['Type'] = file.Type.apply(lambda x : iris.target_names[x])

In [208]:
file.groupby(file.Type).describe()

sepal length (cm)                                              \
                       count   mean       std  min    25%  50%  75%  max   
Type                                                                       
setosa                  50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
versicolor              50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
virginica               50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

           sepal width (cm)         ... petal length (cm)       \
                      count   mean  ...               75%  max   
Type                                ...                          
setosa                 50.0  3.428  ...             1.575  1.9   
versicolor             50.0  2.770  ...             4.600  5.1   
virginica              50.0  2.974  ...             5.875  6.9   

           petal width (cm)                                            
                      count   mean       std  min  25%  50%  75%  max  
Type                                                                   
setosa                 50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6  
versicolor             50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8  
virginica              50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

In [209]:
X = file.drop('Type', axis='columns')
Y = file.Type

# Regular train test split method to categorize the data

In [210]:
from sklearn.model_selection import train_test_split

In [211]:
train_X, test_X, train_y, test_y = train_test_split(X, Y, test_size=0.2)

In [212]:
from sklearn.svm import SVC

In [213]:
model = SVC( C=1.0,
    kernel='rbf')

In [214]:
model.fit(train_X, train_y)

SVC()

In [215]:
model.score(test_X, test_y)

1.0

Here as we reload the data values in the train test split model we will be getting differnt data models and also we can have varying results hence to overcome this we have to use k fold model

# K fold model for testing and training the dataset 

In [216]:
from sklearn.model_selection import KFold

In [217]:
kf = KFold(n_splits=5)

In [218]:
# for train_index, test_index in kf.split(X):
#     train_X, test_X = X[train_index], X[test_index]
#     train_y, test_y = Y[train_index], X[test_index]

Above line of code will be used for the purpose finding the training and testing data for k number of folds but we will use predefined module for the same

In [219]:
from sklearn.model_selection import cross_val_score

In [220]:
cv1 = cross_val_score(SVC(C = 10, kernel='rbf', gamma='auto'), X, Y, cv=5)

In [221]:
cv1

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [222]:
cv2 = cross_val_score(SVC(C = 20, kernel = 'rbf', gamma = 'auto'), X, Y, cv = 5)

In [223]:
cv2

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [224]:
cv3 = cross_val_score(SVC(C = 30, kernel='linear', gamma='auto'), X, Y, cv=5)

In [225]:
cv3

array([1. , 1. , 0.9, 0.9, 1. ])

Here we have whole things manually one by one and it is quite a task that can bore us. Hence we can use for loop so that we can iterate through and make our task simple

In [226]:
import numpy as np
score_val = {}
C_value = [10, 20, 15] 
k_value = ['linear', 'rbf']
for c in C_value:
    for k in k_value:
        cvs = cross_val_score(SVC(C=c, kernel=k, gamma='auto'), X, Y, cv = 5)
        score_val[str(c)+"_"+k] = np.average(cvs)

In [227]:
score_val

{'10_linear': 0.9733333333333334,
 '10_rbf': 0.9800000000000001,
 '20_linear': 0.9666666666666666,
 '20_rbf': 0.9666666666666668,
 '15_linear': 0.9666666666666666,
 '15_rbf': 0.9733333333333334}

Here we have used for loop but it can be done in few lines using gridSearchCV

In [228]:
from sklearn.model_selection import GridSearchCV

In [229]:
model = GridSearchCV(SVC(gamma='auto'),{
    'C' : [10, 20, 15], 
    'kernel' : ['linear', 'rbf']
}, cv= 5, return_train_score = False)

In [230]:
model.fit(X, Y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 15], 'kernel': ['linear', 'rbf']})

In [248]:
model.cv_results_

{'mean_fit_time': array([0.00349998, 0.00476608, 0.00334177, 0.00303426, 0.00378089,
        0.00299263]),
 'std_fit_time': array([4.53145429e-04, 1.32331350e-03, 5.52228664e-04, 7.97498707e-05,
        7.62467453e-04, 9.00256545e-04]),
 'mean_score_time': array([0.00284781, 0.00190535, 0.00204468, 0.00240617, 0.00218678,
        0.00247192]),
 'std_score_time': array([0.00080638, 0.00012739, 0.00030201, 0.00047897, 0.00037988,
        0.00047892]),
 'param_C': masked_array(data=[10, 10, 20, 20, 15, 15],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 15, 'kernel': 'linear'},
  {

In [249]:
analysis = pd.DataFrame(model.cv_results_)

In [250]:
analysis

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.003500      0.000453         0.002848        0.000806      10   
1       0.004766      0.001323         0.001905        0.000127      10   
2       0.003342      0.000552         0.002045        0.000302      20   
3       0.003034      0.000080         0.002406        0.000479      20   
4       0.003781      0.000762         0.002187        0.000380      15   
5       0.002993      0.000900         0.002472        0.000479      15   

  param_kernel                         params  split0_test_score  \
0       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
1          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 15, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 15, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.933333                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.933333           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1  
2         0.966667        0.042164                5  
3         0.966667        0.036515                4  
4         0.966667        0.042164                5  
5         0.973333        0.024944                2

In [251]:
analysis = analysis[['param_C', 'param_kernel', 'mean_test_score']]

In [252]:
analysis

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000
2      20       linear         0.966667
3      20          rbf         0.966667
4      15       linear         0.966667
5      15          rbf         0.973333

In [253]:
model.best_params_

{'C': 10, 'kernel': 'rbf'}

In [254]:
model.best_score_

0.9800000000000001

Here we had predefined number of models but we can use randomized model too

In [255]:
from sklearn.model_selection import RandomizedSearchCV

In [256]:
random_model = RandomizedSearchCV(SVC(gamma='auto'), {
    'C' : [10, 15, 20], 
    'kernel' : ['rbf', 'linear']
}, return_train_score=False, n_iter=2 )

In [257]:
random_model.fit(X, Y)

RandomizedSearchCV(estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [10, 15, 20],
                                        'kernel': ['rbf', 'linear']})

In [258]:
file = pd.DataFrame(random_model.cv_results_)

In [259]:
file

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.003786      0.000631         0.002255        0.000545          rbf   
1       0.004492      0.001187         0.003131        0.002000          rbf   

  param_C                      params  split0_test_score  split1_test_score  \
0      10  {'kernel': 'rbf', 'C': 10}           0.966667                1.0   
1      20  {'kernel': 'rbf', 'C': 20}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.966667           0.966667                1.0         0.980000   
1           0.900000           0.966667                1.0         0.966667   

   std_test_score  rank_test_score  
0        0.016330                1  
1        0.036515                2

In [260]:
random_model.best_index_

0

In [261]:
random_model.best_params_

{'kernel': 'rbf', 'C': 10}

In [262]:
random_model.best_score_

0.9800000000000001

In [263]:
# This can be useful when we have limited power of calculations and we want to improve then yes we should do this

We can use different models at the same time so that they can be used on the same data and we will get to know which model is best

In [277]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [278]:
model_params = {
    'svc' : {
        'name' : SVC(gamma='auto'), 
        'params' : {
            'C' : [10, 15, 20], 
            'kernel' : ['rbf', 'linear']
        }
    }, 
    
    'random_forest' :{
        'name' : RandomForestClassifier(), 
        'params' : {
            'n_estimators' : [10, 100, 150]
        }
    }, 
    
    'l_regression' : {
        'name' : LogisticRegression(solver='liblinear',multi_class='auto'), 
        'params' : {
            'C' : [1,5,10]
     }
  }
}

In [280]:
scores = []

for model_n, model_p in model_params.items():
    my_model = GridSearchCV(model_p['name'], model_p['params'], return_train_score=False, cv=3)
    my_model.fit(X, Y)
    scores.append({
        'Name' : model_n,
        'Score' : my_model.best_score_ , 
        'Parameters' : my_model.best_params_, 
        'Best_Params':my_model.best_index_
    })

In [281]:
scores

[{'Name': 'svc',
  'Score': 0.98,
  'Parameters': {'C': 10, 'kernel': 'rbf'},
  'Best_Params': 0},
 {'Name': 'random_forest',
  'Score': 0.9666666666666667,
  'Parameters': {'n_estimators': 100},
  'Best_Params': 1},
 {'Name': 'l_regression',
  'Score': 0.9733333333333333,
  'Parameters': {'C': 10},
  'Best_Params': 2}]

In [282]:
pd.DataFrame(scores)

Name     Score                  Parameters  Best_Params
0            svc  0.980000  {'C': 10, 'kernel': 'rbf'}            0
1  random_forest  0.966667       {'n_estimators': 100}            1
2   l_regression  0.973333                   {'C': 10}            2